--SELECT
--ID, CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER
--FROM
--dbCUSTOMERS

--INSERT INTO dbCUSTOMERS
--(CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER)
--VALUES
--('ÇÝÐDEN ÇINAR','ÝZMÝR','1984-09-15','BORNOVA','K')

--INSERT INTO [dbo].[dbCUSTOMERS] 
--(CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER) 
--VALUES
--('AYÞEN DURMAZ','ANTALYA','2000-04-23','MANAVGAT','K')

--SELECT * FROM [dbo].[dbCUSTOMERS]

--UPDATE dbCUSTOMERS SET NATION = 'RUS',AGE=26

--SELECT DATEDIFF(YEAR,'2000-06-19',GETDATE())

--BURADA DATEDIFF(YEAR,'ÝLK TARÝH','SON TARÝH') BURADA YEAR KULLARAK FARKI YIL TÜRÜNDEN ALDIK
--UPDATE dbCUSTOMERS SET NATION = 'RUS',AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())

--DELETE FROM dbCUSTOMERS

--TRUNCATE KULLANIMI, TABLOYU ÝLK OLUÞTURDUÐUMUZ HALÝNE DÖNÜÞTÜREN BÝR KOMUTTUR, ÝÇÝNDEKÝ TÜM VERÝLERÝ SÝLÝYOR
--BURADA TÜM VERÝLERÝ DELETE ÝLE SÝLSEK BÝLE BOÞ OLAN TABLOYA YENÝ BÝR DEÐER EKLEDÝÐÝMÝZ ZAMAN SON SÝLÝNEN SATIRININ ID NUMARASINDAN ÝTÝBAREN DEVAM EDÝYOR
--FAKAT TRUNCATE YAPINCA TÜM VERÝLERÝ SÝLÝYOR VE HEPSÝNÝ SÝLSEK BÝLE YENÝ BÝR SATIR EKLENDÝÐÝ ZAMAN 1 DEN BAÞLAYACAKTIR
--TRUNCATE TABLE DBCUSTOMERS

--WHERE KULLANIMI
SELECT * FROM dbCUSTOMERS
--WHERE dbCUSTOMERS.CUSTOMERNAME='AYÞEN DURMAZ'
--WHERE dbCUSTOMERS.CITY = 'ÝZMÝR'
--WHERE CITY<>'ANTALYA'
--WHERE NOT CITY='ÝZMÝR'
--WHERE BIRTHDATE>'1985-01-01'
--WHERE BIRTHDATE BETWEEN '19840101' AND '19851231'
--UPDATE dbCUSTOMERS SET AGE = DATEDIFF(YEAR,BIRTHDATE,GETDATE())
--WHERE AGE BETWEEN 20 AND 40
--WHERE CUSTOMERNAME LIKE 'AY%'
--WHERE DISTRICT LIKE '%AV%'
--WHERE DISTRICT NOT LIKE '%AV%'
--WHERE CITY IN ('ÝZMÝR','ANTALYA')
--DELETE FROM dbCUSTOMERS WHERE ID=1
--UPDATE dbCUSTOMERS SET NATION = 'TR'
--WHERE AGE > 75

--SELECT * FROM dbCUSTOMERS
--WHERE CITY='ÝSTANBUL'AND GENDER='E' AND DISTRICT = 'Esenler'

--SELECT * FROM dbCUSTOMERS
--WHERE CITY = 'ÝSTANBUL'
--AND GENDER = 'E'
--AND BIRTHDATE BETWEEN '19900101' AND '20000101'

SELECT * FROM dbCUSTOMERS
--WHERE CITY='ÝSTANBUL' OR CITY='ÝZMÝR'
--WHERE CITY IN ('ÝSTANBUL','ÝZMÝR','BURSA')
--WHERE BIRTHDATE BETWEEN '19900101' AND '19980101'
--WHERE BIRTHDATE >='19900101' AND BIRTHDATE <='19980101'
--WHERE NOT BIRTHDATE BETWEEN '19900101' AND '19980101'
--WHERE BIRTHDATE<='19900101' OR BIRTHDATE >='19980101'

--DISTINCT KOMUTUNUN KULLANILMASI, TEKRAR EDEN SATIRLARI TEKÝLLEÞTÝRME AMACIYLA KULLANILIR
SELECT DISTINCT CITY FROM dbCUSTOMERS
SELECT DISTINCT CITY , DISTRICT FROM dbCUSTOMERS
WHERE CITY = 'Ýstanbul'
SELECT DISTINCT GENDER FROM dbCUSTOMERS
SELECT DISTINCT AGE FROM dbCUSTOMERS
WHERE CITY = 'Ýstanbul'

--ORDER BY KULLANIMI
SELECT * FROM dbCUSTOMERS
--GROUP BY (CITY)
--ORDER BY ID ASC,
--AGE ASC
--ORDER BY CUSTOMERNAME ASC
--ORDER BY BIRTHDATE
--WHERE CITY='Ýstanbul'
--ORDER BY CITY ASC,
--DISTRICT ASC,
--CUSTOMERNAME ASC
--ORDER BY 5,2

--TOP KULLANIMI
--SELECT
--TOP 50 PERCENT 
--* FROM DBCUSTOMERS
--ORDER BY CUSTOMERNAME