-- AGREGATE FUNCTIONS --

--SELECT COUNT(*) FROM SALES

--SELECT * FROM SALES 
--ORDER BY AMOUNT DESC

--SELECT MIN(AMOUNT),MAX(AMOUNT),COUNT(*),AVG(AMOUNT) FROM SALES

--SELECT * 
--FROM SALES 
--WHERE DATE_ BETWEEN '2019-01-01' AND '2019-02-01'
--ORDER BY DATE_ ASC

--SELECT SUM(AMOUNT) FROM SALES

--SELECT MIN(TOTALPRICE) AS 'MIN_PRICE',
--MAX(TOTALPRICE) AS 'MAX_PRICE',
--COUNT(FICHENO) AS 'TOTAL_COUNT',
--AVG(TOTALPRICE) AS 'AVERAGE_COUNT',
--SUM(TOTALPRICE) AS 'TOTAL_INCOME'FROM SALES
--WHERE CITY = 'Bursa'

--SELECT MIN(TOTALPRICE) AS 'MIN_PRICE',
--MAX(TOTALPRICE) AS 'MAX_PRICE',
--COUNT(FICHENO) AS 'TOTAL_COUNT',
--AVG(TOTALPRICE) AS 'AVERAGE_COUNT',
--SUM(TOTALPRICE) AS 'TOTAL_INCOME'FROM SALES
--WHERE CITY = 'Ýstanbul'

--SELECT MIN(TOTALPRICE) AS 'MIN_PRICE',
--MAX(TOTALPRICE) AS 'MAX_PRICE',
--COUNT(FICHENO) AS 'TOTAL_COUNT',
--AVG(TOTALPRICE) AS 'AVERAGE_COUNT',
--SUM(TOTALPRICE) AS 'TOTAL_INCOME'FROM SALES
--WHERE CITY = 'Ankara'

--SELECT MIN(TOTALPRICE) AS 'MIN_PRICE',
--MAX(TOTALPRICE) AS 'MAX_PRICE',
--COUNT(FICHENO) AS 'TOTAL_COUNT',
--AVG(TOTALPRICE) AS 'AVERAGE_COUNT',
--SUM(TOTALPRICE) AS 'TOTAL_INCOME'FROM SALES
--WHERE CITY = 'Erzurum'

-- GROUP BY USAGE --
--SELECT TOP(10) 
--CITY,
--MIN(TOTALPRICE) AS 'MIN_PRICE',
--MAX(TOTALPRICE) AS 'MAX_PRICE',
--COUNT(FICHENO) AS 'TOTAL_COUNT',
--AVG(TOTALPRICE) AS 'AVERAGE_COUNT',
--SUM(TOTALPRICE) AS 'TOTAL_INCOME'
--FROM SALES
--GROUP BY (CITY)
--ORDER BY TOTAL_INCOME DESC 

-- GROUP BY EXAMPELS -- 

--SELECT CONVERT(DATE,DATE_) AS DATE2,*
--FROM SALES 
--WHERE CITY = 'ANKARA'
--ORDER BY DATE_


-- TARÝH DÜZENLEME AÇISINDAN GERÇEKTEN DE ÇOK KULLANIÞLI BÝR YÖNTEM
--SELECT *
--FROM SALES 
--WHERE CITY = 'ANKARA'
--ORDER BY DATE_

--UPDATE SALES SET DATE2 = CONVERT(DATE,DATE_)

-- BURADA DATETIME CONVERSIONLARIN ÜZERÝNDE DURDUK GERÇEKTEN ÇOK KULLANIÞLI OLABÝLÝR
--SELECT CONVERT(DATE,'2019-01-01 08:22:48.000')
--SELECT CONVERT(TIME,'2019-01-01 08:22:48.000')
--SELECT CONVERT(DATETIME,'2019-01-01 08:22:48.000')

-- HER GÜNE GÖRE NE KADAR SATIÞ YAPILDIÐINI GÖSTERME-- 
--SELECT DATE2,SUM(TOTALPRICE) AS TOTAL_PRICE 
--FROM SALES 
--WHERE CITY = 'ANKARA'
--GROUP BY DATE2
--ORDER BY DATE2 ASC

--*** ÖNEMLÝ BÝR BÝLGÝ EÐER AGGREGATION FONKSÝYONLARINDAN HERHANGÝ BÝRÝNÝ KULLANIYORSAN
--*** SELECT METODU ÝÇÝNDE KULLANDIÐIN COLONLARI KOMUTUN SONUNDA GROUP BY OLARAK KULLANMAK GEREKÝYOR


--Hazýr baþlýklar için kullanmak istediðim templateler
--########################
--##                    ##
--########################


--############################################
--## BÝR GÜNÜN MAÐAZA BAZLI SATIÞ RAKAMLARI ##
--############################################

SELECT CITY,SUM(TOTALPRICE) AS TOTALPRICE,DATE2 FROM SALES 
WHERE DATE2='2019-01-01'
GROUP BY CITY,DATE2
ORDER BY TOTALPRICE ASC