-- SQL GROUP BY DEVAM--
SELECT DATE2,CITY,SUM(TOTALPRICE) AS TOTALPRICE 
FROM SALES
WHERE DATE2 = '2019-01-01'
GROUP BY DATE2,CITY
ORDER BY DATE2,TOTALPRICE DESC

SELECT CITY,DATE2,SUM(TOTALPRICE) AS TOTALPRICES
FROM SALES
WHERE CITY = 'ANKARA' AND DATE2 BETWEEN '2019-01-01' AND '2019-03-01'
GROUP BY DATE2,CITY
ORDER BY DATE2,CITY ASC 

SELECT FICHENO,AMOUNT AS FICHE_COUNT
FROM SALES
WHERE AMOUNT = 8
GROUP BY FICHENO,AMOUNT
ORDER BY FICHE_COUNT DESC

-- MAÐAZALARIN AYLARA GÖRE SATIÞ RAKAMLARININ HESAPLANMASI

SELECT CITY,MONTHNAME_,SUM(TOTALPRICE) AS MONTH_TOTAL_PRICE, DATE2
FROM SALES
GROUP BY MONTHNAME_,CITY,DATE2
ORDER BY CITY,DATEPART(MONTH,DATE2) ASC,
MONTH_TOTAL_PRICE DESC

SELECT CITY,MONTHNAME_,SUM(TOTALPRICE) AS MONTH_TOTAL_PRICE
FROM SALES
WHERE CITY = 'ARDAHAN'
GROUP BY CITY,MONTHNAME_
ORDER BY CITY,MONTHNAME_

-- AYLARA GÖRE ÝLLERÝN SATIÞLARI
SELECT MONTHNAME_,CITY,SUM(TOTALPRICE) AS MONTH_TOTAL_PRICE
FROM SALES
GROUP BY MONTHNAME_,CITY
ORDER BY MONTHNAME_ ASC,MONTH_TOTAL_PRICE DESC

-- YAZILAN TARÝHÝN AY DEÐERÝNÝ BÝZE DÖNDÜRÜR
--SELECT DATEPART(MONTH,'2019-07-21');

--DATEPART KULLANARAK TARÝHLERÝN AY ÝSÝMLERÝNÝ BELÝRLEDÝK
--UPDATE SALES SET MONTHNAME_ = '01.OCAK' WHERE DATEPART(MONTH,DATE2)=1
--UPDATE SALES SET MONTHNAME_ = '02.SUBAT' WHERE DATEPART(MONTH,DATE2)=2
--UPDATE SALES SET MONTHNAME_ = '03.MART' WHERE DATEPART(MONTH,DATE2)=3
--UPDATE SALES SET MONTHNAME_ = '04.NISAN' WHERE DATEPART(MONTH,DATE2)=4
--UPDATE SALES SET MONTHNAME_ = '05.MAYIS' WHERE DATEPART(MONTH,DATE2)=5
--UPDATE SALES SET MONTHNAME_ = '06.HAZIRAN' WHERE DATEPART(MONTH,DATE2)=6
--UPDATE SALES SET MONTHNAME_ = '07.TEMMUZ' WHERE DATEPART(MONTH,DATE2)=7
--UPDATE SALES SET MONTHNAME_ = '08.AGUSTOS' WHERE DATEPART(MONTH,DATE2)=8
--UPDATE SALES SET MONTHNAME_ = '09.EYLUL' WHERE DATEPART(MONTH,DATE2)=9
--UPDATE SALES SET MONTHNAME_ = '10.EKIM' WHERE DATEPART(MONTH,DATE2)=10
--UPDATE SALES SET MONTHNAME_ = '11.KASIM' WHERE DATEPART(MONTH,DATE2)=11
--UPDATE SALES SET MONTHNAME_ = '12.ARALIK' WHERE DATEPART(MONTH,DATE2)=12

--ÜRÜN KATEGORÝLERÝNE GÖRE SATIÞ RAKAMLARI GETÝRME
SELECT CITY,CATEGORY1 ,CATEGORY2,CATEGORY3 ,CATEGORY4,
COUNT(*) AS ROW_COUNT,
SUM(AMOUNT) AS SOLD_COUNT,
SUM(TOTALPRICE) AS TOTAL_SOLD_PRICE 
FROM SALES
GROUP BY CITY,CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4
ORDER BY CITY,CATEGORY1,CATEGORY2,CATEGORY3,TOTAL_SOLD_PRICE DESC


--MAÐAZALARIN MÜÞTERÝ SAYILARINI GETÝRME
SELECT 
CITY,COUNT(DISTINCT FICHENO) AS CUSTOMER_COUNT,COUNT(*) AS TOTAL_SALE_COUNT
FROM SALES 
WHERE MONTHNAME_ ='01.OCAK'
GROUP BY CITY
ORDER BY CITY

SELECT 
CITY,COUNT(DISTINCT CUSTOMERNAME) AS UNIQUE_CUSTOMER_COUNT,
COUNT(DISTINCT FICHENO) AS CUSTOMER_COUNT,
COUNT(*) AS TOTAL_ITEM_SALE_COUNT
FROM SALES 
WHERE MONTHNAME_ ='01.OCAK'
GROUP BY CITY
-- BURADA UNIQUE MÜÞTERÝ ÝLE FÝÞ SAYILARININ EÞÝT OLDUÐU DEÐERLERÝ GETÝRMÝÞ OLUYORUZ
--HAVING(COUNT(DISTINCT FICHENO)=COUNT(DISTINCT CUSTOMERNAME))
ORDER BY CITY	


-- BELLÝ BÝR CÝRONUN ÜZERÝNDE SATIÞ YAPAN MAÐAZALARI GETÝRMEK--
SELECT CITY,
SUM(TOTALPRICE) AS TOTAL_PRICE,
COUNT(DISTINCT CUSTOMERNAME) AS UNIQUE_CUSTOMER_COUNT
FROM SALES
GROUP BY CITY 
HAVING (COUNT(DISTINCT CUSTOMERNAME)>500
AND SUM(TOTALPRICE)>300000)
--HAVING(SUM(TOTALPRICE)>40000)
ORDER BY SUM(TOTALPRICE) DESC 


-- EÐER AGGRAGET VERÝLERÝ ÝLE FÝLTRE YAPACAÐIMIZ ZAMAN WHERE DEÐÝL 
-- HAVING DURUMUNU KULLANMALIYIZ VE BU GROUP BY 'DAN SONRA GELMESÝ GEREKÝYOR
